### ISSUE TITLE
Read Structure Parsing for NextSeq

### ISSUE THREAD

**Issue by MattWellie** [edm1/error-aware-demultiplexer#1]
![screen shot 2017-09-05 at 10 18 35](https://user-images.githubusercontent.com/5886855/30054321-9e9a62b6-9223-11e7-8c0a-af62f1e92c4a.png)
The method used to parse the read structure from the parameters file is not valid for NextSeq: 

  <Reads>
    <RunInfoRead Number="1" NumCycles="76" IsIndexedRead="N" />
    <RunInfoRead Number="2" NumCycles="8" IsIndexedRead="Y" />
    <RunInfoRead Number="3" NumCycles="76" IsIndexedRead="N" />
  </Reads>

vs. 

  <SequencingStarted>true</SequencingStarted>
  <PlannedRead1Cycles>76</PlannedRead1Cycles>
  <PlannedRead2Cycles>76</PlannedRead2Cycles>
  <PlannedIndex1ReadCycles>8</PlannedIndex1ReadCycles>
  <PlannedIndex2ReadCycles>0</PlannedIndex2ReadCycles>

or in the Setup tag 

    <NumLanes>4</NumLanes>
    <Read1>76</Read1>
    <Read2>76</Read2>
    <Index1Read>8</Index1Read>
    <Index2Read>0</Index2Read>

(Added a screen shot as this displays terribly)

**Comment by jackbartram** [comment]
This was only designed for MiSeq


BW


Jack

________________________________

**Comment by jackbartram** [comment]
where to do you work Matt?

________________________________

**Comment by MattWellie** [comment]
Hi Jack,

I work at GOSH, I believe you've spoken to my supervisor Helena recently.
We are using EAD for some MiSeq data now, collaborating with your previous
group maybe?

Matt

**Comment by MattWellie** [comment]
EAD not designed for NXseq, no changes intended
